apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: scc-demo
spec:
  serviceAccountName: demosa
  containers:
    - image: image-registry.openshift-image-registry.svc:5000/scc-demo/demo
      name: demo
      args:
        - /log/demologs.log
      volumeMounts:
        - name: logs
          mountPath: /log/
      securityContext:
        seLinuxOptions:
          # NOTE: This uses an appropriate SELinux type
          type: spc_t
  restartPolicy: Never
  volumes:
    - name: logs
      hostPath:
        path: /var/log/
        type: Directory
